### ISSUE TITLE
Add support custom routes for different values of headers

### ISSUE THREAD

**Issue by alanJames00** [rahulkrishnan0/request-header-parsing#4]
Hey, @rahulkrishnan0 , I have noticed that you are looking for contributions in your project. 
Here are some suggestions, 
1.  Add API routes for specific header values
2.  Try to add support for custom headers

I would like to contribute to this issues and make the api better.  And can you assign me this issue under hacktoberfest 2023. 
Thank you.

**Comment by rahulkrishnan0** [comment]
@alanJames00, I will look into the that suggestion and let you know.
Great suggestions btw.

**Comment by rahulkrishnan0** [comment]
@alanJames00 Let me know if you can implement those routes. And are you willing to create a PR?
Make sure to checkout our CONTRIBUTING.md

**Comment by alanJames00** [comment]
@rahulkrishnan0 , I have created the PR in #6 . Please review it.

**Comment by rahulkrishnan0** [comment]
@alanJames00 , The PR has been merged.
Amazing work. Looking forward to colab with you in the future.
You can close the issue.
Thanks man
