### ISSUE TITLE
Extend custom header routes to support url encoded params

### ISSUE THREAD

**Issue by alanJames00** [rahulkrishnan0/request-header-parsing#7]
The current custom header routes are only fixed in nature. Many developers make use of custom headers that they write. also many uncommon browsers and tools like postman, insomnia does also send uncommon headers. So extending the custom headers to support url encoded params. Probably using request params.

**Comment by rahulkrishnan0** [comment]
I have merged the PR. You may close the issue.
Thanks  for the contribution.

**Comment by alanJames00** [comment]
Looking forward to work with you.
